//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace CWI.PKOL.Webservice {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FakturaAdd {
        
        private string queryIdField;
        
        private PracownikPKOL pracownikField;
        
        private Faktura fakturaField;
        
        private System.DateTime umowaOdField;
        
        private System.DateTime umowaDoField;
        
        private decimal nettoField;
        
        private decimal vATField;
        
        private decimal bruttoField;
        
        private System.DateTime dataRozliczeniaField;
        
        private FormaWspolpracy formaWspolpracyField;
        
        private string numerKontaGlownegoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Faktura Faktura {
            get {
                return this.fakturaField;
            }
            set {
                this.fakturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime UmowaOd {
            get {
                return this.umowaOdField;
            }
            set {
                this.umowaOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime UmowaDo {
            get {
                return this.umowaDoField;
            }
            set {
                this.umowaDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Netto {
            get {
                return this.nettoField;
            }
            set {
                this.nettoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Brutto {
            get {
                return this.bruttoField;
            }
            set {
                this.bruttoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataRozliczenia {
            get {
                return this.dataRozliczeniaField;
            }
            set {
                this.dataRozliczeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormaWspolpracy FormaWspolpracy {
            get {
                return this.formaWspolpracyField;
            }
            set {
                this.formaWspolpracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumerKontaGlownego {
            get {
                return this.numerKontaGlownegoField;
            }
            set {
                this.numerKontaGlownegoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class PracownikPKOL {
        
        private string numerKadrowyField;
        
        private string akronimField;
        
        private string loginField;
        
        private string imieField;
        
        private string nazwiskoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string NumerKadrowy {
            get {
                return this.numerKadrowyField;
            }
            set {
                this.numerKadrowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Akronim {
            get {
                return this.akronimField;
            }
            set {
                this.akronimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Imie {
            get {
                return this.imieField;
            }
            set {
                this.imieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Nazwisko {
            get {
                return this.nazwiskoField;
            }
            set {
                this.nazwiskoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class Faktura {
        
        private string numerFakturyField;
        
        private string opisField;
        
        private System.Nullable<System.DateTime> odField;
        
        private System.Nullable<System.DateTime> doField;
        
        private FakturaPozycja[] pozycjeField;
        
        private System.Nullable<System.DateTime> terminPlatnosciField;
        
        private decimal prowizjaField;
        
        private bool czyZaplaconaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string NumerFaktury {
            get {
                return this.numerFakturyField;
            }
            set {
                this.numerFakturyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> Od {
            get {
                return this.odField;
            }
            set {
                this.odField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> Do {
            get {
                return this.doField;
            }
            set {
                this.doField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Pozycja", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FakturaPozycja[] Pozycje {
            get {
                return this.pozycjeField;
            }
            set {
                this.pozycjeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> TerminPlatnosci {
            get {
                return this.terminPlatnosciField;
            }
            set {
                this.terminPlatnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Prowizja {
            get {
                return this.prowizjaField;
            }
            set {
                this.prowizjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CzyZaplacona {
            get {
                return this.czyZaplaconaField;
            }
            set {
                this.czyZaplaconaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Common.xsd")]
    public partial class FakturaPozycja {
        
        private decimal nettoField;
        
        private decimal vATField;
        
        private decimal bruttoField;
        
        private string nazwaSkladnikaField;
        
        private string opisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Netto {
            get {
                return this.nettoField;
            }
            set {
                this.nettoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VAT {
            get {
                return this.vATField;
            }
            set {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Brutto {
            get {
                return this.bruttoField;
            }
            set {
                this.bruttoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NazwaSkladnika {
            get {
                return this.nazwaSkladnikaField;
            }
            set {
                this.nazwaSkladnikaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public enum FormaWspolpracy {
        
        /// <remarks/>
        Pracownik,
        
        /// <remarks/>
        Zleceniobiorca,
        
        /// <remarks/>
        Współpracownik,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class FakturaAddResponse {
        
        private string queryIdField;
        
        private Info infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Info Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class Info {
        
        private bool wystapilBladField;
        
        private InfoKomunikat[] komunikatyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool WystapilBlad {
            get {
                return this.wystapilBladField;
            }
            set {
                this.wystapilBladField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Komunikat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public InfoKomunikat[] Komunikaty {
            get {
                return this.komunikatyField;
            }
            set {
                this.komunikatyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Common.xsd")]
    public partial class InfoKomunikat {
        
        private TypKomunikatu typField;
        
        private string kodField;
        
        private string opisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TypKomunikatu Typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public enum TypKomunikatu {
        
        /// <remarks/>
        Informacja,
        
        /// <remarks/>
        Ostrzeżenie,
        
        /// <remarks/>
        Błąd,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KalendarzSwiatGet {
        
        private string queryIdField;
        
        private int rokField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Rok {
            get {
                return this.rokField;
            }
            set {
                this.rokField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KalendarzSwiatGetResponse {
        
        private string queryIdField;
        
        private KalendarzSwiatGetResponseDzienWolny[] dniWolneField;
        
        private Info infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DzienWolny", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public KalendarzSwiatGetResponseDzienWolny[] DniWolne {
            get {
                return this.dniWolneField;
            }
            set {
                this.dniWolneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Info Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KalendarzSwiatGetResponseDzienWolny {
        
        private System.DateTime dataField;
        
        private string nazwaField;
        
        private bool czyUstawowoWolneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CzyUstawowoWolne {
            get {
                return this.czyUstawowoWolneField;
            }
            set {
                this.czyUstawowoWolneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NieobecnosciZastepstwaGet {
        
        private string queryIdField;
        
        private Identifier pracownikField;
        
        private System.DateTime odField;
        
        private System.DateTime doField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Identifier Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Od {
            get {
                return this.odField;
            }
            set {
                this.odField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Do {
            get {
                return this.doField;
            }
            set {
                this.doField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class Identifier {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Login", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("NumerKadrowy", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":Login")]
        Login,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":NumerKadrowy")]
        NumerKadrowy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NieobecnosciZastepstwaGetResponse {
        
        private string queryIdField;
        
        private NieobecnosciZastepstwaGetResponseNieobecnosc[] nieobecnosciField;
        
        private System.DateTime dataZakonczeniaField;
        
        private bool czyPracujeField;
        
        private Info infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Nieobecnosc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NieobecnosciZastepstwaGetResponseNieobecnosc[] Nieobecnosci {
            get {
                return this.nieobecnosciField;
            }
            set {
                this.nieobecnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DataZakonczenia {
            get {
                return this.dataZakonczeniaField;
            }
            set {
                this.dataZakonczeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CzyPracuje {
            get {
                return this.czyPracujeField;
            }
            set {
                this.czyPracujeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Info Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class NieobecnosciZastepstwaGetResponseNieobecnosc {
        
        private PracownikPKOL zastepujacyField;
        
        private PracownikPKOL zastepowanyField;
        
        private System.DateTime odField;
        
        private System.DateTime doField;
        
        private string rodzajNieobecnosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL Zastepujacy {
            get {
                return this.zastepujacyField;
            }
            set {
                this.zastepujacyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL Zastepowany {
            get {
                return this.zastepowanyField;
            }
            set {
                this.zastepowanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Od {
            get {
                return this.odField;
            }
            set {
                this.odField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Do {
            get {
                return this.doField;
            }
            set {
                this.doField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RodzajNieobecnosci {
            get {
                return this.rodzajNieobecnosciField;
            }
            set {
                this.rodzajNieobecnosciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PodstawoweDaneGet {
        
        private string queryIdField;
        
        private Identifier pracownikField;
        
        private System.Nullable<FormaWspolpracy> formaWspolpracyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Identifier Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<FormaWspolpracy> FormaWspolpracy {
            get {
                return this.formaWspolpracyField;
            }
            set {
                this.formaWspolpracyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class PodstawoweDaneGetResponse {
        
        private string queryIdField;
        
        private PracownikPKOL pracownikField;
        
        private string departamentField;
        
        private JednostkaOrganizacyjna jednostkaOrganizacyjnaField;
        
        private string mPKField;
        
        private string telefonKomorkowyField;
        
        private string telefonStacjonarnyField;
        
        private string emailField;
        
        private FormaWspolpracy formaWspolpracyField;
        
        private StatusWspolpracy statusWspolpracyField;
        
        private string nIPField;
        
        private string rEGONField;
        
        private string nazwaDzialalnosciField;
        
        private OpisStanowiska opisStanowiskaField;
        
        private string lokalizacjaMiejscaPracyField;
        
        private Przelozeni przelozeniField;
        
        private Info infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Departament {
            get {
                return this.departamentField;
            }
            set {
                this.departamentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JednostkaOrganizacyjna JednostkaOrganizacyjna {
            get {
                return this.jednostkaOrganizacyjnaField;
            }
            set {
                this.jednostkaOrganizacyjnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MPK {
            get {
                return this.mPKField;
            }
            set {
                this.mPKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonKomorkowy {
            get {
                return this.telefonKomorkowyField;
            }
            set {
                this.telefonKomorkowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TelefonStacjonarny {
            get {
                return this.telefonStacjonarnyField;
            }
            set {
                this.telefonStacjonarnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormaWspolpracy FormaWspolpracy {
            get {
                return this.formaWspolpracyField;
            }
            set {
                this.formaWspolpracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatusWspolpracy StatusWspolpracy {
            get {
                return this.statusWspolpracyField;
            }
            set {
                this.statusWspolpracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NIP {
            get {
                return this.nIPField;
            }
            set {
                this.nIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGON {
            get {
                return this.rEGONField;
            }
            set {
                this.rEGONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NazwaDzialalnosci {
            get {
                return this.nazwaDzialalnosciField;
            }
            set {
                this.nazwaDzialalnosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public OpisStanowiska OpisStanowiska {
            get {
                return this.opisStanowiskaField;
            }
            set {
                this.opisStanowiskaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LokalizacjaMiejscaPracy {
            get {
                return this.lokalizacjaMiejscaPracyField;
            }
            set {
                this.lokalizacjaMiejscaPracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Przelozeni Przelozeni {
            get {
                return this.przelozeniField;
            }
            set {
                this.przelozeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Info Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class JednostkaOrganizacyjna {
        
        private string kodField;
        
        private string nazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public enum StatusWspolpracy {
        
        /// <remarks/>
        Aktywny,
        
        /// <remarks/>
        Nieaktywny,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class OpisStanowiska {
        
        private string stanowiskoField;
        
        private string funkcjaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stanowisko {
            get {
                return this.stanowiskoField;
            }
            set {
                this.stanowiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Funkcja {
            get {
                return this.funkcjaField;
            }
            set {
                this.funkcjaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Common.xsd")]
    public partial class Przelozeni {
        
        private PracownikPKOL bezposredniPrzelozonyField;
        
        private PracownikPKOL dyrektorDepartamentuField;
        
        private PracownikPKOL czlonekZarzaduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL BezposredniPrzelozony {
            get {
                return this.bezposredniPrzelozonyField;
            }
            set {
                this.bezposredniPrzelozonyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL DyrektorDepartamentu {
            get {
                return this.dyrektorDepartamentuField;
            }
            set {
                this.dyrektorDepartamentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL CzlonekZarzadu {
            get {
                return this.czlonekZarzaduField;
            }
            set {
                this.czlonekZarzaduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ZajeciaKomorniczePlatnosciGet {
        
        private string queryIdField;
        
        private Identifier pracownikField;
        
        private System.DateTime odField;
        
        private System.DateTime doField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Identifier Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Od {
            get {
                return this.odField;
            }
            set {
                this.odField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime Do {
            get {
                return this.doField;
            }
            set {
                this.doField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ZajeciaKomorniczePlatnosciGetResponse {
        
        private string queryIdField;
        
        private ZajeciaKomorniczePlatnosciGetResponseWyplaty wyplatyField;
        
        private Info infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZajeciaKomorniczePlatnosciGetResponseWyplaty Wyplaty {
            get {
                return this.wyplatyField;
            }
            set {
                this.wyplatyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Info Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZajeciaKomorniczePlatnosciGetResponseWyplaty {
        
        private PracownikPKOL pracownikField;
        
        private ZajeciaKomorniczePlatnosciGetResponseWyplatyWyplata[] wyplataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PracownikPKOL Pracownik {
            get {
                return this.pracownikField;
            }
            set {
                this.pracownikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Wyplata", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZajeciaKomorniczePlatnosciGetResponseWyplatyWyplata[] Wyplata {
            get {
                return this.wyplataField;
            }
            set {
                this.wyplataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ZajeciaKomorniczePlatnosciGetResponseWyplatyWyplata {
        
        private Faktura fakturaField;
        
        private string numerKontaGlownegoField;
        
        private FormaWspolpracy formaWspolpracyField;
        
        private string kontoSAPField;
        
        private string kontoLEOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Faktura Faktura {
            get {
                return this.fakturaField;
            }
            set {
                this.fakturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string NumerKontaGlownego {
            get {
                return this.numerKontaGlownegoField;
            }
            set {
                this.numerKontaGlownegoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FormaWspolpracy FormaWspolpracy {
            get {
                return this.formaWspolpracyField;
            }
            set {
                this.formaWspolpracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontoSAP {
            get {
                return this.kontoSAPField;
            }
            set {
                this.kontoSAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KontoLEO {
            get {
                return this.kontoLEOField;
            }
            set {
                this.kontoLEOField = value;
            }
        }
    }
}
